{% set name = "de-bundesrat" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/de-bundesrat-{{ version }}.tar.gz
  sha256: d817a1e6f804ad06a3abb7283b5bca16c0293abecfaa3d9c05055b81d513386a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

test:
  imports:
    - deutschland.bundesrat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bundesAPI/bundesrat-api
  summary: 'Bundesrat: Live Informationen'
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
